"""Generate docs/EVIDENCE_PER_LEVEL.md — the CoSAI MCP Security v2.0
evidence-per-level annex (v2.0 open question #4) — from the in-package control
catalog (cosai_mcp/assurance/controls.py). The doc is never hand-edited:
tests/test_evidence_annex.py fails when it is out of sync.

    python scripts/gen_evidence_annex.py            # rewrite the doc
    python scripts/gen_evidence_annex.py --check    # exit 1 if stale
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

from cosai_mcp.assurance.controls import CONTROLS, DIMENSIONS, PROFILE_VERSION
from cosai_mcp.assurance.models import Control, Strength

ROOT = Path(__file__).resolve().parent.parent
DOC = ROOT / "docs" / "EVIDENCE_PER_LEVEL.md"
README = ROOT / "README.md"
_START = "<!-- assurance-matrix:start (generated by scripts/gen_evidence_annex.py) -->"
_END = "<!-- assurance-matrix:end -->"

# Reference implementations an operator can deploy and cite as evidence.
# cosai-mcp = cosai_mcp.middleware / telemetry; mcp-armor = server-side SDK.
# mcp-armor EnvelopeEngine is opt-in and only sees the client's _meta/headers
# behind ArmorMiddleware (or the sidecar); not on @guard.protect / the FastMCP
# per-tool hook. Not yet in a PyPI release.
_ARMOR_CAVEAT = (" — mcp-armor: opt-in, enforced only behind ArmorMiddleware/sidecar, "
                 "not yet in a released version")

# (module, attribute path) for every cosai-mcp symbol named below — resolved by
# tests/test_evidence_annex.py so the annex never cites a symbol that is gone.
COSAI_SYMBOLS: tuple[tuple[str, str], ...] = (
    ("cosai_mcp.middleware.request_meta", "validate_request_metadata"),
    ("cosai_mcp.middleware.request_meta", "reconcile_meta"),
    ("cosai_mcp.middleware", "CoSAIStack.check_request_envelope"),
    ("cosai_mcp.middleware.state", "HandleRegistry"),
    ("cosai_mcp.middleware.state", "RequestStateSealer"),
    ("cosai_mcp.telemetry.ocsf", "build_mcp_api_activity"),
    ("cosai_mcp.middleware.audit", "AuditLogger"),
    ("cosai_mcp.telemetry.tracecontext", "preserve_client_trace"),
)

REFERENCE_IMPL: dict[str, str] = {
    "TN-04": "cosai-mcp `middleware.request_meta.validate_request_metadata` / "
             "`CoSAIStack.check_request_envelope`; mcp-armor `EnvelopeEngine` "
             f"(`T7.enforce_request_envelope`){_ARMOR_CAVEAT}",
    "SD-01": "cosai-mcp `middleware.state.HandleRegistry`; mcp-armor "
             "`explicit_state.HandleRegistry` (not yet in a released version)",
    "SD-02": "cosai-mcp `middleware.request_meta.reconcile_meta`; mcp-armor "
             f"`EnvelopeEngine` / `request_envelope.reconcile_meta`{_ARMOR_CAVEAT}",
    "SD-03": "cosai-mcp `middleware.state.RequestStateSealer`; mcp-armor "
             "`explicit_state.RequestStateSealer` (not yet in a released version)",
    "LO-01": "cosai-mcp `telemetry.ocsf.build_mcp_api_activity` (OCSF 6003, "
             "keyed parameter digests); hash-chained `middleware.audit.AuditLogger`",
    "LO-02": "cosai-mcp `telemetry.ocsf.build_mcp_api_activity` "
             "(`cosai_agentic.delegation_path`)",
    "LO-03": "cosai-mcp / mcp-armor `tracecontext` (canonical traceparent, "
             "identity-free bounded baggage, client trace id preserved)",
    "LO-04": "cosai-mcp `telemetry.ocsf.build_mcp_api_activity` "
             "(`unmapped.cosai_agentic`)",
}


def _cell(c: Control, level: int) -> str:
    req = c.requirement(level)
    if req is None:
        return "—"
    return "**MUST**" if req.strength is Strength.MUST else "SHOULD"


def _scanner_line(c: Control) -> str:
    parts: list[str] = []
    if c.verify_with and c.blackbox_max_level:
        parts.append(f"can **prove** up to L{c.blackbox_max_level} when "
                     + ", ".join(f"`{p}`" for p in c.verify_with)
                     + " all pass conclusively")
    required = [p for p in c.probe_threats if p not in c.optional_probes]
    if required:
        parts.append("can **disprove** via " + ", ".join(f"`{p}`" for p in required))
    if c.optional_probes:
        parts.append("disproof via "
                     + ", ".join(f"`{p}`" for p in c.optional_probes)
                     + " — required when the target exposes that surface "
                     "(2026-07-28 / extension), otherwise optional")
    return "; ".join(parts) if parts else "no black-box signal — evidence only"


def render() -> str:
    out: list[str] = [
        "# CoSAI MCP Security v2.0 — Evidence per Assurance Level (annex)",
        "",
        "<!-- GENERATED by scripts/gen_evidence_annex.py from "
        "cosai_mcp/assurance/controls.py — do not edit by hand. -->",
        "",
        f"Profile: `{PROFILE_VERSION}` · {len(CONTROLS)} controls · "
        f"{len(DIMENSIONS)} dimensions · levels L1–L4 (v2.0 §3.3).",
        "",
        "This annex answers v2.0 open question #4 — *what evidence demonstrates "
        "each control at each level* — for the controls in §3.3.2, and says "
        "which part an automated verifier (§3.3.5) can establish on its own.",
        "",
        "## How `cosai scan --assurance-level N` decides",
        "",
        "Checked in this order (first match wins):",
        "",
        "| Verdict | Meaning |",
        "|---|---|",
        "| `not_required` | The control has no requirement at the claimed level. |",
        "| `fail` | A linked probe or scenario produced a conclusive finding. "
        "Evidence cannot override it. |",
        "| `unverified` (gap) | A linked test that must run did not run or was "
        "never conclusive — including a passive check (e.g. `T06`) that is present "
        "in the scan but inconclusive, and an *optional* disproof test that became "
        "required because the target exposes its surface (speaks 2026-07-28 / the "
        "Tasks extension). Evidence cannot stand in for it. |",
        "| `attested` | The operator supplied a hashed artifact (`--evidence DIR`). "
        "Recorded, not judged — and it takes precedence over a passing proof, so "
        "omit evidence for a control you want scanner-verified. |",
        "| `pass` | No evidence was supplied, the claimed level is at or below the "
        "control's black-box ceiling, and every *proving* probe (`verify_with`) "
        "passed conclusively. |",
        "| `unverified` (default) | Anything else: \"evidence only\" controls "
        "without evidence, levels above the black-box ceiling, inconclusive "
        "proving probes. |",
        "",
        "A level is `met` only when every MUST at that level is `pass`; "
        "`met_with_attestation` when every MUST is `pass` or `attested`; "
        "`not_met` when any MUST fails; otherwise `indeterminate`. The level "
        "claim, the effective scan scope and the evidence hashes are embedded in "
        "the Ed25519-signed scorecard.",
        "",
        "Evidence manifest (`DIR/evidence.json`), bound to the scanned target:",
        "",
        "```json",
        '{"schema_version": "1.0", "target": "https://mcp.example.com/mcp",',
        ' "controls": {"ID-02": {"artifact": "authz/iss-validation-test.txt",',
        '                        "note": "RFC 9207 iss check, CI job #812"}}}',
        "```",
        "",
        "**What to attest:** an artifact that demonstrates the requirement text "
        "below at the claimed level — a configuration export, a test run, a "
        "policy, or a log sample — for the deployment named in `target`. Where a "
        "reference implementation is listed, its configuration plus its "
        "regression test output is acceptable evidence.",
        "",
    ]
    for dim in DIMENSIONS:
        controls = [c for c in CONTROLS if c.dimension == dim]
        out += [f"## {dim}", "",
                "| Control | L1 | L2 | L3 | L4 | Scanner |",
                "|---|:-:|:-:|:-:|:-:|---|"]
        for c in controls:
            out.append(f"| {c.control_id} {c.title} | "
                       + " | ".join(_cell(c, lvl) for lvl in (1, 2, 3, 4))
                       + f" | {_scanner_line(c)} |")
        out.append("")
        for c in controls:
            out += [f"### {c.control_id} — {c.title}", "",
                    f"MCP threats: {', '.join(c.mcp_t) or '—'}", ""]
            for lvl in (1, 2, 3, 4):
                req = c.requirement(lvl)
                if req is not None:
                    out.append(f"- **L{lvl} {req.strength.value.upper()}** — {req.text}")
            out += ["", f"Scanner: {_scanner_line(c)}."]
            if c.control_id in REFERENCE_IMPL:
                out.append(f"Reference implementation: {REFERENCE_IMPL[c.control_id]}.")
            out.append("")
    return "\n".join(out).rstrip() + "\n"


def render_readme_block() -> str:
    """Per-dimension × level summary embedded in README.md between markers."""
    rows = ["| Dimension | Controls | MUST @ L1 | L2 | L3 | L4 | Scanner can disprove | "
            "Scanner can prove |", "|---|:-:|:-:|:-:|:-:|:-:|:-:|:-:|"]
    for dim in DIMENSIONS:
        cs = [c for c in CONTROLS if c.dimension == dim]
        musts = [sum(1 for c in cs if (r := c.requirement(lvl)) is not None
                     and r.strength is Strength.MUST) for lvl in (1, 2, 3, 4)]
        disprove = sum(1 for c in cs if c.probe_threats)
        optional = sum(1 for c in cs if c.optional_probes and not c.probe_threats)
        disprove_cell = f"{disprove}" + (f" (+{optional} surface-dependent)" if optional else "")
        prove = [f"{c.control_id} (≤L{c.blackbox_max_level})"
                 for c in cs if c.verify_with and c.blackbox_max_level]
        rows.append(f"| {dim} | {len(cs)} | " + " | ".join(str(m) for m in musts)
                    + f" | {disprove_cell} | {', '.join(prove) or '—'} |")
    return "\n".join([
        _START,
        "",
        f"`cosai scan TARGET --assurance-level N [--evidence DIR]` checks a deployment "
        f"against the CoSAI MCP Security v2.0 §3.3 profile ({len(CONTROLS)} controls). "
        "A black-box scan can *disprove* many controls but *prove* only a few — the "
        "rest need hashed operator evidence and cap the result at "
        "`met_with_attestation`. Per-control requirements and what to attest: "
        "[docs/EVIDENCE_PER_LEVEL.md](docs/EVIDENCE_PER_LEVEL.md).",
        "",
        *rows,
        "",
        _END,
    ])


class MarkerError(ValueError):
    pass


def _splice_readme(text: str) -> str:
    if _START not in text or _END not in text:
        raise MarkerError("README.md lacks the assurance-matrix markers")
    start, end = text.index(_START), text.index(_END) + len(_END)
    return text[:start] + render_readme_block() + text[end:]


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args(argv)
    text = render()
    readme = README.read_text(encoding="utf-8")
    try:
        new_readme = _splice_readme(readme)
    except MarkerError as exc:
        print(f"{exc} — add {_START!r} / {_END!r}", file=sys.stderr)
        return 2
    if args.check:
        current = DOC.read_text(encoding="utf-8") if DOC.exists() else ""
        if current != text or readme != new_readme:
            print("evidence annex / README matrix stale — run "
                  "scripts/gen_evidence_annex.py", file=sys.stderr)
            return 1
        return 0
    DOC.write_text(text, encoding="utf-8")
    README.write_text(new_readme, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
